query GetUserActionsByUserId(
  $last_timestamp: BigInt = "3322572585300000000"
  $user_id: String = ""
) {
  userActions(
    first: 50
    orderBy: timestamp_plus_log_index
    orderDirection: desc
    where: { timestamp_lt: $last_timestamp, user_id: $user_id, action_type_not_in: [read_notification_action] }
  ) {
    id
    timestamp
    action_type
    user_id
    token_id
    receipt_id
    create_listing_action {
      price
      listing {
        seller_id
        price
        token_id
      }
    }
    # listing
    update_listing_action {
      old_price
      new_price
      listing {
        seller_id
        token_id
        price
      }
    }
    remove_listing_action {
      listing {
        token_id
        seller_id
      }
    }
    buy_listing_action {
      buyer_id
      listing {
        token_id
        seller_id
        price
      }
    }
    # offer
    create_offering_action {
      price
    }
    update_offering_action {
      old_price
      new_price
    }
    accept_offering_action {
      buyer_id
      seller_id
      payout_balance # this is the amount the seller gets
      payment_balance # this is the amount of the offer
    }

    # nft
    nft_mint_action {
      token_id
      owner_id
    }
    nft_transfer_action {
      token_id
      old_owner_id
      new_owner_id
    }
    nft_burn_action {
      token_id
    }
  }
}
